version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: maven
    commit-message:
      prefix: dependencies
    directory: /
    schedule:
      interval: daily
    groups:
      spring-boot:
        applies-to: version-updates
        patterns:
          - 'spring-boot-starter*'
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
