version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: maven
    commit-message:
      prefix: dependencies
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: "org.activiti:activiti-spring-boot-starter"
        versions:
          - 8.1.0 # until the bug https://github.com/Activiti/Activiti/issues/4491 is fixed.
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
