#
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Huawei Inc.
#
---
name: xpanse-cd-docker-only
# This job generates the API doc for the version requested and uploads it to SwaggerHub.
on:
  workflow_dispatch:
    inputs:
      VersionToBeUploaded:
        type: string
        description: Enter the version of the API that must be uploaded

env:
  BOT_USER_NAME: eclipse-xpanse-bot
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository == 'eclipse-xpanse/xpanse'
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: v${{github.event.inputs.VersionToBeUploaded}}

      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Generate API doc
        run: mvn verify -DskipTests -Pgenerate-openapi-doc

      - name: Upload API to SwaggerHub
        run: mvn io.swagger:swaggerhub-maven-plugin:upload -Dversion=${{github.event.inputs.VersionToBeUploaded}} -Duser=${{ secrets.SWAGGERHUB_USER }} -Dtoken=${{ secrets.SWAGGERHUB_API_KEY }}
